v1
boyarintsev1/java-shareit pull request #1
Opened 2024-01-12 17:38 UTC by boyarintsev1

2024-01-12 18:54 UTC, kriwsha requested changes

2024-01-12 18:54 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> + * Класс BookingDto ("заказ") содержит описание заказа Booking, которое будет возвращено пользователю. Поля:
Перечислять все поля родительского класса необязательно. Представьте, у вас будет несколько уровней наследования. Последний класс будет содержать огромное количество строк комментария.

2024-01-12 18:54 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> + * id — уникальный идентификатор бронирования;
Подобное документирование я бы рекомендовал разбить для каждого поля отдельно. Так будет для изучающего ваш код понятнее.

2024-01-12 18:54 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> + * REJECTED — бронирование отклонено владельцем, CANCELED — бронирование отменено создателем
Здесь вы себе усложняете работу. Если разработчик захочет посмотреть, какие есть статусы, он перейдет в энамку. Но если вы хотите их держать в комментарии вам всегда потребуется поддерживать актуальность этого комментария. А в командной разработке это нереально. В один момент кто-то просто забудет. И будет у вас неконсистентное документирование.

2024-01-12 18:54 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +   // @ResponseStatus(HttpStatus.BAD_REQUEST)
Закомментированный код лучше удалять

2024-01-12 18:54 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        itemsOfUser.clear();
Не до конца понимаю назначение этого списка. Я бы понял подобную заботу о памяти, если бы мы писали на С, где нет сборщика мусора. Но на Java такой проблемы нет. И в принципе не рекомендуется в бинах (а контроллер - это тоже бин) хранить состояние, несмотря на то, что это всего лишь кэш.

2024-01-12 18:54 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        itemDtoList.clear();
Та же рекомендация, что и для другого списка.

2024-01-12 18:54 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +   request — если вещь была создана по запросу другого пользователя, то в этом поле будет ID соответствующего запроса.
Здесь и дальше такая же рекомендация, как и в предыдущих комментариях

2024-01-12 18:54 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +    String message;
К этим полям та же рекомендация - не создавать состояние в бине (это считается плохой практикой)

2024-01-12 18:54 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +        if (!items.containsKey(id)) {
Здесь, конечно, все корректно. Но восклицательных знак в начале может быть случайно пропущен. Поэтому в таких ситуациях я бы рекомендовал инвертировать условие. То есть сначала проверяется позитивный сценарий, а потом негативный.

2024-01-12 18:54 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> + * TODO Sprint add-controllers.
Везде такие красивые комментарии писали, а здесь решили оставить туду

2024-01-12 18:54 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    private List<UserDto> userDtoList = new ArrayList<>();
Та же рекомендация - не создавать состояние бина

2024-01-12 18:54 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +        } else {
Вот здесь else можно даже не создавать. Тогда у вас не будет чуть меньше отступов. Но сразу скажу - есть и противники такого подхода. Они выступают за полноценную if-else конструкцию для наглядности

2024-01-13 07:29 UTC, boyarintsev1 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> + * Класс BookingDto ("заказ") содержит описание заказа Booking, которое будет возвращено пользователю. Поля:
Исправил во всех Dto-классах

2024-01-13 07:29 UTC, boyarintsev1 commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> + * id — уникальный идентификатор бронирования;
Исправил во всех моделях классов

2024-01-13 07:30 UTC, boyarintsev1 commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> + * REJECTED — бронирование отклонено владельцем, CANCELED — бронирование отменено создателем
Исправлено

2024-01-13 07:30 UTC, boyarintsev1 commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +   // @ResponseStatus(HttpStatus.BAD_REQUEST)
Пропустил, исправляюсь

2024-01-13 07:31 UTC, boyarintsev1 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        itemsOfUser.clear();
Спасибо за замечение. Я не продумал этот момент.
Исправляю

2024-01-13 07:31 UTC, boyarintsev1 commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +    String message;
Исправлено.

2024-01-13 07:31 UTC, boyarintsev1 commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +        if (!items.containsKey(id)) {
Исправлено.

2024-01-13 07:31 UTC, boyarintsev1 commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> + * TODO Sprint add-controllers.
:))))

2024-01-13 07:32 UTC, boyarintsev1 commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    private List<UserDto> userDtoList = new ArrayList<>();
Исправлено.

2024-01-13 07:32 UTC, boyarintsev1 commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +        } else {
Убрал else.

2024-01-13 17:29 UTC, kriwsha approved these changes

2024-01-14 09:03 UTC, merged